### ISSUE TITLE
Add sharding key based on tenant

### ISSUE THREAD

**Issue by einari** [dolittle-extensions/ReadModels.MongoDB#11]
With primary focus on our own usage of CosmosDB - we might need some more flexibility on this, possibly right now only turn on or off.

The guidelines from Microsoft: 
https://docs.microsoft.com/en-us/azure/cosmos-db/partition-data

**Comment by woksin** [comment]
@einari Should we take a day where we can look at this together so that we can make wrappers for the Mongo stuff properly,  without having to re-implement the wheel entirely

**Comment by einari** [comment]
We can do some work on Tuesday

**Comment by woksin** [comment]
Waiting to do this til we have implemented the redesign of  our event store and read models database
